import Fastify from "fastify";
import cors from "@fastify/cors";
import puppeteer from "puppeteer";
import { z } from "zod";

const fastify = Fastify({ logger: true });
fastify.register(cors);

// ── Health check ──────────────────────────────────────────────────────────────
fastify.get("/health", async () => ({ status: "ok", service: "docgen-svc" }));

// ── PDF Generation endpoint ───────────────────────────────────────────────────
const GenerateSchema = z.object({
  html: z.string().min(100, "HTML content too short"),
  filename: z.string().optional().default("nyaymitra_document"),
  format: z.enum(["A4", "Letter"]).optional().default("A4"),
  landscape: z.boolean().optional().default(false),
});

fastify.post("/v1/docgen/pdf", async (request, reply) => {
  let browser;
  try {
    const body = GenerateSchema.parse(request.body);

    // Launch Puppeteer (headless)
    browser = await puppeteer.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--font-render-hinting=none",
      ],
    });

    const page = await browser.newPage();

    // Inject the HTML content directly
    await page.setContent(body.html, { waitUntil: "networkidle0" });

    // Inject Google Fonts if not already present (for Cormorant Garamond)
    await page.evaluate(() => {
      if (!document.querySelector('link[href*="fonts.googleapis"]')) {
        const link = document.createElement("link");
        link.rel = "stylesheet";
        link.href = "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600&family=Instrument+Sans:wght@400;500;600&display=swap";
        document.head.appendChild(link);
      }
    });

    // Wait a moment for fonts
    await new Promise(r => setTimeout(r, 800));

    // Generate PDF
    const pdfBuffer = await page.pdf({
      format: body.format as "A4" | "Letter",
      landscape: body.landscape,
      printBackground: true,
      margin: {
        top: "20mm",
        right: "15mm",
        bottom: "20mm",
        left: "15mm",
      },
      displayHeaderFooter: true,
      headerTemplate: `<div style="font-size:8px;color:#999;width:100%;text-align:center;font-family:sans-serif;">DRAFT — For Review Only — Nyay Mitra</div>`,
      footerTemplate: `<div style="font-size:8px;color:#999;width:100%;text-align:center;font-family:sans-serif;">Page <span class="pageNumber"></span> of <span class="totalPages"></span> · Generated by Nyay Mitra · Not a substitute for professional legal advice</div>`,
    });

    await browser.close();

    // Return PDF as binary
    reply
      .header("Content-Type", "application/pdf")
      .header("Content-Disposition", `attachment; filename="${body.filename}.pdf"`)
      .header("Content-Length", pdfBuffer.length)
      .send(pdfBuffer);

  } catch (err: any) {
    if (browser) await browser.close().catch(() => {});

    if (err instanceof z.ZodError) {
      return reply.status(400).send({ error: "Validation failed", details: err.errors });
    }

    fastify.log.error(err);
    return reply.status(500).send({ error: "PDF generation failed. Ensure Puppeteer is installed." });
  }
});

// ── HTML → PDF preview (returns base64 for browser preview) ──────────────────
fastify.post("/v1/docgen/preview", async (request, reply) => {
  let browser;
  try {
    const { html } = z.object({ html: z.string().min(100) }).parse(request.body);

    browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    await new Promise(r => setTimeout(r, 500));

    const screenshot = await page.screenshot({ type: "png", fullPage: false });
    await browser.close();

    return reply.send({
      preview: `data:image/png;base64,${Buffer.from(screenshot).toString("base64")}`,
    });

  } catch (err: any) {
    if (browser) await browser.close().catch(() => {});
    fastify.log.error(err);
    return reply.status(500).send({ error: "Preview generation failed." });
  }
});

// ── Start ─────────────────────────────────────────────────────────────────────
const start = async () => {
  try {
    const port = process.env.PORT ? parseInt(process.env.PORT) : 4003;
    await fastify.listen({ port, host: "0.0.0.0" });
    console.log(`docgen-svc running on port ${port}`);
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};

start();
